create table if not exists public.site_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

insert into public.site_settings (key, value)
values (
  'resume_url',
  'https://drive.google.com/file/d/1wIniqDimrqYNiFFfpc5tNNQNyCVt-SNe/view?usp=sharing'
)
on conflict (key) do nothing;

alter table public.site_settings enable row level security;

grant select on public.site_settings to anon, authenticated;
grant update (value, updated_at) on public.site_settings to authenticated;

drop policy if exists "Anyone can read site settings" on public.site_settings;
create policy "Anyone can read site settings"
on public.site_settings
for select
to anon, authenticated
using (true);

drop policy if exists "Admin can update resume URL" on public.site_settings;
create policy "Admin can update resume URL"
on public.site_settings
for update
to authenticated
using (
  key = 'resume_url'
  and lower(auth.jwt() ->> 'email') = lower('jasonjahja@gmail.com')
)
with check (
  key = 'resume_url'
  and lower(auth.jwt() ->> 'email') = lower('jasonjahja@gmail.com')
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  session_id uuid not null,
  event_name text not null check (char_length(event_name) between 1 and 60),
  pathname text not null check (char_length(pathname) between 1 and 180),
  page_type text not null check (page_type in ('home', 'case_study', 'other')),
  project_slug text,
  referrer_host text,
  device_type text not null check (device_type in ('mobile', 'tablet', 'desktop')),
  browser text not null,
  country text,
  properties jsonb not null default '{}'::jsonb
);

create table if not exists public.analytics_web_vitals (
  id bigint generated by default as identity primary key,
  recorded_at timestamptz not null default now(),
  session_id uuid not null,
  metric_id text,
  metric_name text not null check (metric_name in ('TTFB', 'FCP', 'LCP', 'FID', 'CLS', 'INP')),
  value double precision not null check (value >= 0 and value <= 120000),
  rating text check (rating in ('good', 'needs-improvement', 'poor')),
  navigation_type text,
  pathname text not null check (char_length(pathname) between 1 and 180),
  project_slug text,
  device_type text not null check (device_type in ('mobile', 'tablet', 'desktop')),
  browser text not null,
  country text,
  unique (metric_id, metric_name)
);

create index if not exists analytics_events_occurred_at_idx
  on public.analytics_events (occurred_at desc);
create index if not exists analytics_events_event_time_idx
  on public.analytics_events (event_name, occurred_at desc);
create index if not exists analytics_events_path_time_idx
  on public.analytics_events (pathname, occurred_at desc);
create index if not exists analytics_events_project_time_idx
  on public.analytics_events (project_slug, occurred_at desc);
create index if not exists analytics_events_session_time_idx
  on public.analytics_events (session_id, occurred_at desc);
create index if not exists analytics_web_vitals_recorded_at_idx
  on public.analytics_web_vitals (recorded_at desc);
create index if not exists analytics_web_vitals_metric_time_idx
  on public.analytics_web_vitals (metric_name, recorded_at desc);

alter table public.analytics_events enable row level security;
alter table public.analytics_web_vitals enable row level security;

revoke all on public.analytics_events from anon, authenticated;
revoke all on public.analytics_web_vitals from anon, authenticated;
grant all on public.analytics_events to service_role;
grant all on public.analytics_web_vitals to service_role;
grant usage, select on sequence public.analytics_events_id_seq to service_role;
grant usage, select on sequence public.analytics_web_vitals_id_seq to service_role;

comment on table public.analytics_events is
  'First-party portfolio analytics. Stores anonymous session events without IP addresses or raw user agents.';
comment on table public.analytics_web_vitals is
  'First-party Core Web Vitals collected from real portfolio visits.';
